# Generated by Django 4.0.4 on 2022-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(blank=True, db_index=True, default=0, verbose_name='like_count'),
        ),
    ]
